### ISSUE TITLE
latest version of mocha-chai-jest-snapshot is not compatible with chai@"^5.0.0"

### ISSUE THREAD

**Issue by MoonOKC** [mochiya98/mocha-chai-jest-snapshot#20]
Will there be any release to catch up chai@"^5.0.0" as I can not update my chai with :
npm WARN Could not resolve dependency:
npm WARN peer chai@"^4.3.6" from mocha-chai-jest-snapshot@1.1.4

**Comment by piranna** [comment]
Same problem here.

**Comment by blephy** [comment]
Same here

**Comment by tpluscode** [comment]
This appears to be the best snapshotting lib for mocha/chai. At which point do we fork this and continue maintaining?

**Comment by mochiya98** [comment]
Sorry for the delayed response. I was on a long trip. I’ll check on it.

**Comment by mochiya98** [comment]
I’ve realized that there are various heavy obstacles to supporting ESModules. I give up to support it. sorry. Contribution are always welcome.

**Comment by tpluscode** [comment]
I looked at your setup and indeed, the integration tests would be a challenge to rework to support ESM

That said, it should not be necessary to convert the entire package to ESM in order to work with chai v5. Not even a peer dependency on chai is necessary after applying a small change.

PR: https://github.com/mochiya98/mocha-chai-jest-snapshot/pull/21

**Comment by mochiya98** [comment]
Good idea! I'll check it out...

**Comment by mochiya98** [comment]
fixed in 1.1.6 (thanks @tpluscode !)
